// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/**
 * Typed Supabase client — used for auth and any table that exists in the generated schema.
 * If VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY are missing at runtime,
 * auth calls will fail gracefully (no hard throw at module load time, which broke HMR).
 */
export const supabase = createClient<Database>(
  SUPABASE_URL ?? "https://placeholder.supabase.co",
  SUPABASE_PUBLISHABLE_KEY ?? "placeholder-key",
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
  },
);

/**
 * Untyped Supabase client — used ONLY by backend service files that reference tables
 * not yet in the generated Database schema (live_locations, safe_zones, notifications,
 * sos_events). When those tables are created and `supabase gen types` is run, migrate
 * these callers back to the typed `supabase` client above.
 *
 * TODO (backend): Run `supabase gen types typescript --local > src/integrations/supabase/types.ts`
 *   after creating the backend tables, then migrate service files to `supabase`.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const untypedSupabase = supabase as any;
